/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

/**
 *
 * @author HP
 */
public class frmListaPaquetes extends javax.swing.JFrame {

    /**
     * Creates new form ListaPaquetes
     */
    public frmListaPaquetes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        btnMachuPicchu = new javax.swing.JButton();
        btnOllantaytambo = new javax.swing.JButton();
        btnPisaq = new javax.swing.JButton();
        btnQoriqancha = new javax.swing.JButton();
        btnArequipa = new javax.swing.JButton();
        btnTacna = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblKuntur = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMachuPicchu.setText("MACHU PICCHU");
        btnMachuPicchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachuPicchuActionPerformed(evt);
            }
        });

        btnOllantaytambo.setText("OLLANTAYTAMBO");
        btnOllantaytambo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOllantaytamboActionPerformed(evt);
            }
        });

        btnPisaq.setText("PISAQ");
        btnPisaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPisaqActionPerformed(evt);
            }
        });

        btnQoriqancha.setText("QORIQANCHA");
        btnQoriqancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQoriqanchaActionPerformed(evt);
            }
        });

        btnArequipa.setText("AREQUIPA");
        btnArequipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArequipaActionPerformed(evt);
            }
        });

        btnTacna.setText("TACNA");
        btnTacna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacnaActionPerformed(evt);
            }
        });

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblKuntur.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblKuntur.setText("KUNTUR");

        jLabel2.setText("AGENCIA DE VIAJES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnArequipa)
                    .addComponent(btnPisaq)
                    .addComponent(btnMachuPicchu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOllantaytambo)
                    .addComponent(btnQoriqancha)
                    .addComponent(btnTacna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKuntur)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblKuntur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMachuPicchu)
                            .addComponent(btnOllantaytambo))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPisaq)
                            .addComponent(btnQoriqancha))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArequipa)
                            .addComponent(btnTacna))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMachuPicchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMachuPicchuActionPerformed
        // TODO add your handling code here:
        JOptionPanel.ShowMessageDialog(this, "Metodo no implementado");
    }//GEN-LAST:event_btnMachuPicchuActionPerformed

    private void btnOllantaytamboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOllantaytamboActionPerformed
        // TODO add your handling code here:
        JOptionPanel.ShowMessageDialog(this, "Metodo no implementado");
    }//GEN-LAST:event_btnOllantaytamboActionPerformed

    private void btnPisaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPisaqActionPerformed
        // TODO add your handling code here:
        JOptionPanel.ShowMessageDialog(this, "Metodo no implementado");
    }//GEN-LAST:event_btnPisaqActionPerformed

    private void btnQoriqanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQoriqanchaActionPerformed
        // TODO add your handling code here:
        JOptionPanel.ShowMessageDialog(this, "Metodo no implementado");
    }//GEN-LAST:event_btnQoriqanchaActionPerformed

    private void btnArequipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArequipaActionPerformed
        // TODO add your handling code here:
        JOptionPanel.ShowMessageDialog(this, "Metodo no implementado");
    }//GEN-LAST:event_btnArequipaActionPerformed

    private void btnTacnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacnaActionPerformed
        // TODO add your handling code here:
        JOptionPanel.ShowMessageDialog(this, "Metodo no implementado");
    }//GEN-LAST:event_btnTacnaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListaPaquetes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArequipa;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMachuPicchu;
    private javax.swing.JButton btnOllantaytambo;
    private javax.swing.JButton btnPisaq;
    private javax.swing.JButton btnQoriqancha;
    private javax.swing.JButton btnTacna;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblKuntur;
    // End of variables declaration//GEN-END:variables
}
